# This allows it to run on faster containers
sudo: false

language: android
env:
  matrix:
    - ANDROID_SDKS=android-23,sysimg-23 ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
android:
  components:
    - platform-tools
    - build-tools-23.0.0
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
cache:
   directories:
   - $HOME/.gradle/caches/

before_install:
  - chmod +x gradlew

#before_script:
#  # Make sure emulator has started before running tests
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &  
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck
# connectedCheck
#  - ./gradlew assembleDebug 
#  - ./gradlew connectedAndroidTestDebug --info

