baseurl = "http://spacecowboy.github.io/NoNonsense-FilePicker/"
languageCode = "en-us"
title = "NoNonsense FilePicker"
theme = "hugo-material-docs"
metadataformat = "toml"
canonifyurls = true
PygmentsCodeFences = true
PygmentsStyle = "friendly"
PygmentsOptions = ""
#pygmentsuseclasses = true # Will use css file in /static/
# Enable Google Analytics by entering your tracking id
#googleAnalytics = ""

[params]
	# General information
	author = "SpaceCowboy"
	description = "An extensible and flexible file-picker for Android."
	copyright = "Released under the Mozilla Public License 2.0"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/spacecowboy/NoNonsense-FilePicker"

	version = ""
	logo = ""
	favicon = ""

	permalink = ":slug"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light green"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = "spacecowboy"


[[menu.main]]
	name   = "Readme"
	url    = "readme/"
	weight = 0

[[menu.main]]
	name   = "Changelog"
	url    = "changelog/"
	weight = 10

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 20

[[menu.main]]
	name   = "Examples"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
    latexDashes = true
	plainIDAnchors = true
